######################################################################
# Automatically generated by qmake (3.0) ?? 5? 8 23:57:01 2019
######################################################################

TEMPLATE = app
TARGET = 4
INCLUDEPATH += .

# Input
HEADERS += ui_hellodialog.h
FORMS += helloworld.ui
SOURCES += main.cpp
QT+=widgets
