######################################################################
# Automatically generated by qmake (3.0) ?? 5? 8 23:31:45 2019
######################################################################

TEMPLATE = app
TARGET = 3
INCLUDEPATH += .

# Input
SOURCES += main.cpp
greaterThan(QT_MAJOR_VERSION,4):QT+=widgets
